algoritmo "EXERCICIO-C"
var
   A: Vetor[1..4,1..5] de inteiro
   X,Y: inteiro
inicio
   //ENTRADA DE DADOS: MATRIZ 'A'
   Para X := 1 ate 4 faca
      Para Y := 1 ate 5 faca
         Leia(A[X,Y])
      FimPara
   FimPara
   //SAÍDA DE DADOS: MATRIZ 'A'
   Para X := 1 ate 4 faca
        Para Y := 1 ate 5 faca
        Escreva(A[X,Y]:5)
        FimPara
        EscrevaL()
   FimPara
fimalgoritmo








